//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.11 at 03:29:58 PM IST 
//


package org.ovirt.engine.sdk.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperatingSystem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperatingSystem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="boot" type="{}Boot" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="kernel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="initrd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cmdline" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperatingSystem", propOrder = {
    "boot",
    "kernel",
    "initrd",
    "cmdline"
})
public class OperatingSystem {

    protected List<Boot> boot;
    protected String kernel;
    protected String initrd;
    protected String cmdline;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the boot property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the boot property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBoot().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boot }
     * 
     * 
     */
    public List<Boot> getBoot() {
        if (boot == null) {
            boot = new ArrayList<Boot>();
        }
        return this.boot;
    }

    public boolean isSetBoot() {
        return ((this.boot!= null)&&(!this.boot.isEmpty()));
    }

    public void unsetBoot() {
        this.boot = null;
    }

    /**
     * Gets the value of the kernel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKernel() {
        return kernel;
    }

    /**
     * Sets the value of the kernel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKernel(String value) {
        this.kernel = value;
    }

    public boolean isSetKernel() {
        return (this.kernel!= null);
    }

    /**
     * Gets the value of the initrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitrd() {
        return initrd;
    }

    /**
     * Sets the value of the initrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitrd(String value) {
        this.initrd = value;
    }

    public boolean isSetInitrd() {
        return (this.initrd!= null);
    }

    /**
     * Gets the value of the cmdline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdline() {
        return cmdline;
    }

    /**
     * Sets the value of the cmdline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdline(String value) {
        this.cmdline = value;
    }

    public boolean isSetCmdline() {
        return (this.cmdline!= null);
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

}
